/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorRecipeRouteImport } from './routes/editor/recipe'
import { Route as EditorLoot_tableRouteImport } from './routes/editor/loot_table'
import { Route as EditorEnchantmentRouteImport } from './routes/editor/enchantment'
import { Route as EditorRecipeOverviewRouteImport } from './routes/editor/recipe/overview'
import { Route as EditorRecipeMainRouteImport } from './routes/editor/recipe/main'
import { Route as EditorLoot_tablePoolsRouteImport } from './routes/editor/loot_table/pools'
import { Route as EditorLoot_tableOverviewRouteImport } from './routes/editor/loot_table/overview'
import { Route as EditorLoot_tableMainRouteImport } from './routes/editor/loot_table/main'
import { Route as EditorEnchantmentTechnicalRouteImport } from './routes/editor/enchantment/technical'
import { Route as EditorEnchantmentSlotsRouteImport } from './routes/editor/enchantment/slots'
import { Route as EditorEnchantmentSimulationRouteImport } from './routes/editor/enchantment/simulation'
import { Route as EditorEnchantmentOverviewRouteImport } from './routes/editor/enchantment/overview'
import { Route as EditorEnchantmentMainRouteImport } from './routes/editor/enchantment/main'
import { Route as EditorEnchantmentItemsRouteImport } from './routes/editor/enchantment/items'
import { Route as EditorEnchantmentFindRouteImport } from './routes/editor/enchantment/find'
import { Route as EditorEnchantmentExclusiveRouteImport } from './routes/editor/enchantment/exclusive'

const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRecipeRoute = EditorRecipeRouteImport.update({
  id: '/recipe',
  path: '/recipe',
  getParentRoute: () => EditorRoute,
} as any)
const EditorLoot_tableRoute = EditorLoot_tableRouteImport.update({
  id: '/loot_table',
  path: '/loot_table',
  getParentRoute: () => EditorRoute,
} as any)
const EditorEnchantmentRoute = EditorEnchantmentRouteImport.update({
  id: '/enchantment',
  path: '/enchantment',
  getParentRoute: () => EditorRoute,
} as any)
const EditorRecipeOverviewRoute = EditorRecipeOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => EditorRecipeRoute,
} as any)
const EditorRecipeMainRoute = EditorRecipeMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => EditorRecipeRoute,
} as any)
const EditorLoot_tablePoolsRoute = EditorLoot_tablePoolsRouteImport.update({
  id: '/pools',
  path: '/pools',
  getParentRoute: () => EditorLoot_tableRoute,
} as any)
const EditorLoot_tableOverviewRoute =
  EditorLoot_tableOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => EditorLoot_tableRoute,
  } as any)
const EditorLoot_tableMainRoute = EditorLoot_tableMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => EditorLoot_tableRoute,
} as any)
const EditorEnchantmentTechnicalRoute =
  EditorEnchantmentTechnicalRouteImport.update({
    id: '/technical',
    path: '/technical',
    getParentRoute: () => EditorEnchantmentRoute,
  } as any)
const EditorEnchantmentSlotsRoute = EditorEnchantmentSlotsRouteImport.update({
  id: '/slots',
  path: '/slots',
  getParentRoute: () => EditorEnchantmentRoute,
} as any)
const EditorEnchantmentSimulationRoute =
  EditorEnchantmentSimulationRouteImport.update({
    id: '/simulation',
    path: '/simulation',
    getParentRoute: () => EditorEnchantmentRoute,
  } as any)
const EditorEnchantmentOverviewRoute =
  EditorEnchantmentOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => EditorEnchantmentRoute,
  } as any)
const EditorEnchantmentMainRoute = EditorEnchantmentMainRouteImport.update({
  id: '/main',
  path: '/main',
  getParentRoute: () => EditorEnchantmentRoute,
} as any)
const EditorEnchantmentItemsRoute = EditorEnchantmentItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => EditorEnchantmentRoute,
} as any)
const EditorEnchantmentFindRoute = EditorEnchantmentFindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => EditorEnchantmentRoute,
} as any)
const EditorEnchantmentExclusiveRoute =
  EditorEnchantmentExclusiveRouteImport.update({
    id: '/exclusive',
    path: '/exclusive',
    getParentRoute: () => EditorEnchantmentRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRouteWithChildren
  '/editor/enchantment': typeof EditorEnchantmentRouteWithChildren
  '/editor/loot_table': typeof EditorLoot_tableRouteWithChildren
  '/editor/recipe': typeof EditorRecipeRouteWithChildren
  '/editor/enchantment/exclusive': typeof EditorEnchantmentExclusiveRoute
  '/editor/enchantment/find': typeof EditorEnchantmentFindRoute
  '/editor/enchantment/items': typeof EditorEnchantmentItemsRoute
  '/editor/enchantment/main': typeof EditorEnchantmentMainRoute
  '/editor/enchantment/overview': typeof EditorEnchantmentOverviewRoute
  '/editor/enchantment/simulation': typeof EditorEnchantmentSimulationRoute
  '/editor/enchantment/slots': typeof EditorEnchantmentSlotsRoute
  '/editor/enchantment/technical': typeof EditorEnchantmentTechnicalRoute
  '/editor/loot_table/main': typeof EditorLoot_tableMainRoute
  '/editor/loot_table/overview': typeof EditorLoot_tableOverviewRoute
  '/editor/loot_table/pools': typeof EditorLoot_tablePoolsRoute
  '/editor/recipe/main': typeof EditorRecipeMainRoute
  '/editor/recipe/overview': typeof EditorRecipeOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRouteWithChildren
  '/editor/enchantment': typeof EditorEnchantmentRouteWithChildren
  '/editor/loot_table': typeof EditorLoot_tableRouteWithChildren
  '/editor/recipe': typeof EditorRecipeRouteWithChildren
  '/editor/enchantment/exclusive': typeof EditorEnchantmentExclusiveRoute
  '/editor/enchantment/find': typeof EditorEnchantmentFindRoute
  '/editor/enchantment/items': typeof EditorEnchantmentItemsRoute
  '/editor/enchantment/main': typeof EditorEnchantmentMainRoute
  '/editor/enchantment/overview': typeof EditorEnchantmentOverviewRoute
  '/editor/enchantment/simulation': typeof EditorEnchantmentSimulationRoute
  '/editor/enchantment/slots': typeof EditorEnchantmentSlotsRoute
  '/editor/enchantment/technical': typeof EditorEnchantmentTechnicalRoute
  '/editor/loot_table/main': typeof EditorLoot_tableMainRoute
  '/editor/loot_table/overview': typeof EditorLoot_tableOverviewRoute
  '/editor/loot_table/pools': typeof EditorLoot_tablePoolsRoute
  '/editor/recipe/main': typeof EditorRecipeMainRoute
  '/editor/recipe/overview': typeof EditorRecipeOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/editor': typeof EditorRouteWithChildren
  '/editor/enchantment': typeof EditorEnchantmentRouteWithChildren
  '/editor/loot_table': typeof EditorLoot_tableRouteWithChildren
  '/editor/recipe': typeof EditorRecipeRouteWithChildren
  '/editor/enchantment/exclusive': typeof EditorEnchantmentExclusiveRoute
  '/editor/enchantment/find': typeof EditorEnchantmentFindRoute
  '/editor/enchantment/items': typeof EditorEnchantmentItemsRoute
  '/editor/enchantment/main': typeof EditorEnchantmentMainRoute
  '/editor/enchantment/overview': typeof EditorEnchantmentOverviewRoute
  '/editor/enchantment/simulation': typeof EditorEnchantmentSimulationRoute
  '/editor/enchantment/slots': typeof EditorEnchantmentSlotsRoute
  '/editor/enchantment/technical': typeof EditorEnchantmentTechnicalRoute
  '/editor/loot_table/main': typeof EditorLoot_tableMainRoute
  '/editor/loot_table/overview': typeof EditorLoot_tableOverviewRoute
  '/editor/loot_table/pools': typeof EditorLoot_tablePoolsRoute
  '/editor/recipe/main': typeof EditorRecipeMainRoute
  '/editor/recipe/overview': typeof EditorRecipeOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/editor'
    | '/editor/enchantment'
    | '/editor/loot_table'
    | '/editor/recipe'
    | '/editor/enchantment/exclusive'
    | '/editor/enchantment/find'
    | '/editor/enchantment/items'
    | '/editor/enchantment/main'
    | '/editor/enchantment/overview'
    | '/editor/enchantment/simulation'
    | '/editor/enchantment/slots'
    | '/editor/enchantment/technical'
    | '/editor/loot_table/main'
    | '/editor/loot_table/overview'
    | '/editor/loot_table/pools'
    | '/editor/recipe/main'
    | '/editor/recipe/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/editor'
    | '/editor/enchantment'
    | '/editor/loot_table'
    | '/editor/recipe'
    | '/editor/enchantment/exclusive'
    | '/editor/enchantment/find'
    | '/editor/enchantment/items'
    | '/editor/enchantment/main'
    | '/editor/enchantment/overview'
    | '/editor/enchantment/simulation'
    | '/editor/enchantment/slots'
    | '/editor/enchantment/technical'
    | '/editor/loot_table/main'
    | '/editor/loot_table/overview'
    | '/editor/loot_table/pools'
    | '/editor/recipe/main'
    | '/editor/recipe/overview'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/editor'
    | '/editor/enchantment'
    | '/editor/loot_table'
    | '/editor/recipe'
    | '/editor/enchantment/exclusive'
    | '/editor/enchantment/find'
    | '/editor/enchantment/items'
    | '/editor/enchantment/main'
    | '/editor/enchantment/overview'
    | '/editor/enchantment/simulation'
    | '/editor/enchantment/slots'
    | '/editor/enchantment/technical'
    | '/editor/loot_table/main'
    | '/editor/loot_table/overview'
    | '/editor/loot_table/pools'
    | '/editor/recipe/main'
    | '/editor/recipe/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  EditorRoute: typeof EditorRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/recipe': {
      id: '/editor/recipe'
      path: '/recipe'
      fullPath: '/editor/recipe'
      preLoaderRoute: typeof EditorRecipeRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/loot_table': {
      id: '/editor/loot_table'
      path: '/loot_table'
      fullPath: '/editor/loot_table'
      preLoaderRoute: typeof EditorLoot_tableRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/enchantment': {
      id: '/editor/enchantment'
      path: '/enchantment'
      fullPath: '/editor/enchantment'
      preLoaderRoute: typeof EditorEnchantmentRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/recipe/overview': {
      id: '/editor/recipe/overview'
      path: '/overview'
      fullPath: '/editor/recipe/overview'
      preLoaderRoute: typeof EditorRecipeOverviewRouteImport
      parentRoute: typeof EditorRecipeRoute
    }
    '/editor/recipe/main': {
      id: '/editor/recipe/main'
      path: '/main'
      fullPath: '/editor/recipe/main'
      preLoaderRoute: typeof EditorRecipeMainRouteImport
      parentRoute: typeof EditorRecipeRoute
    }
    '/editor/loot_table/pools': {
      id: '/editor/loot_table/pools'
      path: '/pools'
      fullPath: '/editor/loot_table/pools'
      preLoaderRoute: typeof EditorLoot_tablePoolsRouteImport
      parentRoute: typeof EditorLoot_tableRoute
    }
    '/editor/loot_table/overview': {
      id: '/editor/loot_table/overview'
      path: '/overview'
      fullPath: '/editor/loot_table/overview'
      preLoaderRoute: typeof EditorLoot_tableOverviewRouteImport
      parentRoute: typeof EditorLoot_tableRoute
    }
    '/editor/loot_table/main': {
      id: '/editor/loot_table/main'
      path: '/main'
      fullPath: '/editor/loot_table/main'
      preLoaderRoute: typeof EditorLoot_tableMainRouteImport
      parentRoute: typeof EditorLoot_tableRoute
    }
    '/editor/enchantment/technical': {
      id: '/editor/enchantment/technical'
      path: '/technical'
      fullPath: '/editor/enchantment/technical'
      preLoaderRoute: typeof EditorEnchantmentTechnicalRouteImport
      parentRoute: typeof EditorEnchantmentRoute
    }
    '/editor/enchantment/slots': {
      id: '/editor/enchantment/slots'
      path: '/slots'
      fullPath: '/editor/enchantment/slots'
      preLoaderRoute: typeof EditorEnchantmentSlotsRouteImport
      parentRoute: typeof EditorEnchantmentRoute
    }
    '/editor/enchantment/simulation': {
      id: '/editor/enchantment/simulation'
      path: '/simulation'
      fullPath: '/editor/enchantment/simulation'
      preLoaderRoute: typeof EditorEnchantmentSimulationRouteImport
      parentRoute: typeof EditorEnchantmentRoute
    }
    '/editor/enchantment/overview': {
      id: '/editor/enchantment/overview'
      path: '/overview'
      fullPath: '/editor/enchantment/overview'
      preLoaderRoute: typeof EditorEnchantmentOverviewRouteImport
      parentRoute: typeof EditorEnchantmentRoute
    }
    '/editor/enchantment/main': {
      id: '/editor/enchantment/main'
      path: '/main'
      fullPath: '/editor/enchantment/main'
      preLoaderRoute: typeof EditorEnchantmentMainRouteImport
      parentRoute: typeof EditorEnchantmentRoute
    }
    '/editor/enchantment/items': {
      id: '/editor/enchantment/items'
      path: '/items'
      fullPath: '/editor/enchantment/items'
      preLoaderRoute: typeof EditorEnchantmentItemsRouteImport
      parentRoute: typeof EditorEnchantmentRoute
    }
    '/editor/enchantment/find': {
      id: '/editor/enchantment/find'
      path: '/find'
      fullPath: '/editor/enchantment/find'
      preLoaderRoute: typeof EditorEnchantmentFindRouteImport
      parentRoute: typeof EditorEnchantmentRoute
    }
    '/editor/enchantment/exclusive': {
      id: '/editor/enchantment/exclusive'
      path: '/exclusive'
      fullPath: '/editor/enchantment/exclusive'
      preLoaderRoute: typeof EditorEnchantmentExclusiveRouteImport
      parentRoute: typeof EditorEnchantmentRoute
    }
  }
}

interface EditorEnchantmentRouteChildren {
  EditorEnchantmentExclusiveRoute: typeof EditorEnchantmentExclusiveRoute
  EditorEnchantmentFindRoute: typeof EditorEnchantmentFindRoute
  EditorEnchantmentItemsRoute: typeof EditorEnchantmentItemsRoute
  EditorEnchantmentMainRoute: typeof EditorEnchantmentMainRoute
  EditorEnchantmentOverviewRoute: typeof EditorEnchantmentOverviewRoute
  EditorEnchantmentSimulationRoute: typeof EditorEnchantmentSimulationRoute
  EditorEnchantmentSlotsRoute: typeof EditorEnchantmentSlotsRoute
  EditorEnchantmentTechnicalRoute: typeof EditorEnchantmentTechnicalRoute
}

const EditorEnchantmentRouteChildren: EditorEnchantmentRouteChildren = {
  EditorEnchantmentExclusiveRoute: EditorEnchantmentExclusiveRoute,
  EditorEnchantmentFindRoute: EditorEnchantmentFindRoute,
  EditorEnchantmentItemsRoute: EditorEnchantmentItemsRoute,
  EditorEnchantmentMainRoute: EditorEnchantmentMainRoute,
  EditorEnchantmentOverviewRoute: EditorEnchantmentOverviewRoute,
  EditorEnchantmentSimulationRoute: EditorEnchantmentSimulationRoute,
  EditorEnchantmentSlotsRoute: EditorEnchantmentSlotsRoute,
  EditorEnchantmentTechnicalRoute: EditorEnchantmentTechnicalRoute,
}

const EditorEnchantmentRouteWithChildren =
  EditorEnchantmentRoute._addFileChildren(EditorEnchantmentRouteChildren)

interface EditorLoot_tableRouteChildren {
  EditorLoot_tableMainRoute: typeof EditorLoot_tableMainRoute
  EditorLoot_tableOverviewRoute: typeof EditorLoot_tableOverviewRoute
  EditorLoot_tablePoolsRoute: typeof EditorLoot_tablePoolsRoute
}

const EditorLoot_tableRouteChildren: EditorLoot_tableRouteChildren = {
  EditorLoot_tableMainRoute: EditorLoot_tableMainRoute,
  EditorLoot_tableOverviewRoute: EditorLoot_tableOverviewRoute,
  EditorLoot_tablePoolsRoute: EditorLoot_tablePoolsRoute,
}

const EditorLoot_tableRouteWithChildren =
  EditorLoot_tableRoute._addFileChildren(EditorLoot_tableRouteChildren)

interface EditorRecipeRouteChildren {
  EditorRecipeMainRoute: typeof EditorRecipeMainRoute
  EditorRecipeOverviewRoute: typeof EditorRecipeOverviewRoute
}

const EditorRecipeRouteChildren: EditorRecipeRouteChildren = {
  EditorRecipeMainRoute: EditorRecipeMainRoute,
  EditorRecipeOverviewRoute: EditorRecipeOverviewRoute,
}

const EditorRecipeRouteWithChildren = EditorRecipeRoute._addFileChildren(
  EditorRecipeRouteChildren,
)

interface EditorRouteChildren {
  EditorEnchantmentRoute: typeof EditorEnchantmentRouteWithChildren
  EditorLoot_tableRoute: typeof EditorLoot_tableRouteWithChildren
  EditorRecipeRoute: typeof EditorRecipeRouteWithChildren
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorEnchantmentRoute: EditorEnchantmentRouteWithChildren,
  EditorLoot_tableRoute: EditorLoot_tableRouteWithChildren,
  EditorRecipeRoute: EditorRecipeRouteWithChildren,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  EditorRoute: EditorRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
