/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LangRouteImport } from './routes/$lang'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LangIndexRouteImport } from './routes/$lang/index'
import { Route as LangWorldRouteImport } from './routes/$lang/world'
import { Route as LangStudioEditorRouteImport } from './routes/$lang/studio/editor'
import { Route as LangStudioEditorRecipeRouteImport } from './routes/$lang/studio/editor/recipe'
import { Route as LangStudioEditorLoot_tableRouteImport } from './routes/$lang/studio/editor/loot_table'
import { Route as LangStudioEditorGithubRouteImport } from './routes/$lang/studio/editor/github'
import { Route as LangStudioEditorEnchantmentRouteImport } from './routes/$lang/studio/editor/enchantment'
import { Route as LangStudioEditorDebugRouteImport } from './routes/$lang/studio/editor/debug'
import { Route as LangStudioEditorChangesRouteImport } from './routes/$lang/studio/editor/changes'
import { Route as LangStudioEditorRecipeOverviewRouteImport } from './routes/$lang/studio/editor/recipe/overview'
import { Route as LangStudioEditorRecipeMainRouteImport } from './routes/$lang/studio/editor/recipe/main'
import { Route as LangStudioEditorLoot_tablePoolsRouteImport } from './routes/$lang/studio/editor/loot_table/pools'
import { Route as LangStudioEditorLoot_tableOverviewRouteImport } from './routes/$lang/studio/editor/loot_table/overview'
import { Route as LangStudioEditorLoot_tableMainRouteImport } from './routes/$lang/studio/editor/loot_table/main'
import { Route as LangStudioEditorEnchantmentYggdrasilRouteImport } from './routes/$lang/studio/editor/enchantment/yggdrasil'
import { Route as LangStudioEditorEnchantmentTechnicalRouteImport } from './routes/$lang/studio/editor/enchantment/technical'
import { Route as LangStudioEditorEnchantmentSlotsRouteImport } from './routes/$lang/studio/editor/enchantment/slots'
import { Route as LangStudioEditorEnchantmentSimulationRouteImport } from './routes/$lang/studio/editor/enchantment/simulation'
import { Route as LangStudioEditorEnchantmentOverviewRouteImport } from './routes/$lang/studio/editor/enchantment/overview'
import { Route as LangStudioEditorEnchantmentMainRouteImport } from './routes/$lang/studio/editor/enchantment/main'
import { Route as LangStudioEditorEnchantmentItemsRouteImport } from './routes/$lang/studio/editor/enchantment/items'
import { Route as LangStudioEditorEnchantmentFindRouteImport } from './routes/$lang/studio/editor/enchantment/find'
import { Route as LangStudioEditorEnchantmentExclusiveRouteImport } from './routes/$lang/studio/editor/enchantment/exclusive'
import { Route as LangStudioEditorEnchantmentDntRouteImport } from './routes/$lang/studio/editor/enchantment/dnt'
import { Route as LangStudioEditorChangesVoxelRouteImport } from './routes/$lang/studio/editor/changes/voxel'
import { Route as LangStudioEditorChangesPatchRouteImport } from './routes/$lang/studio/editor/changes/patch'
import { Route as LangStudioEditorChangesMainRouteImport } from './routes/$lang/studio/editor/changes/main'
import { Route as LangStudioEditorChangesEditRouteImport } from './routes/$lang/studio/editor/changes/edit'
import { Route as LangStudioEditorChangesDiffRouteImport } from './routes/$lang/studio/editor/changes/diff'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LangRoute = LangRouteImport.update({
  id: '/$lang',
  path: '/$lang',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LangIndexRoute = LangIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LangRoute,
} as any)
const LangWorldRoute = LangWorldRouteImport.update({
  id: '/world',
  path: '/world',
  getParentRoute: () => LangRoute,
} as any)
const LangStudioEditorRoute = LangStudioEditorRouteImport.update({
  id: '/studio/editor',
  path: '/studio/editor',
  getParentRoute: () => LangRoute,
} as any)
const LangStudioEditorRecipeRoute = LangStudioEditorRecipeRouteImport.update({
  id: '/recipe',
  path: '/recipe',
  getParentRoute: () => LangStudioEditorRoute,
} as any)
const LangStudioEditorLoot_tableRoute =
  LangStudioEditorLoot_tableRouteImport.update({
    id: '/loot_table',
    path: '/loot_table',
    getParentRoute: () => LangStudioEditorRoute,
  } as any)
const LangStudioEditorGithubRoute = LangStudioEditorGithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => LangStudioEditorRoute,
} as any)
const LangStudioEditorEnchantmentRoute =
  LangStudioEditorEnchantmentRouteImport.update({
    id: '/enchantment',
    path: '/enchantment',
    getParentRoute: () => LangStudioEditorRoute,
  } as any)
const LangStudioEditorDebugRoute = LangStudioEditorDebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => LangStudioEditorRoute,
} as any)
const LangStudioEditorChangesRoute = LangStudioEditorChangesRouteImport.update({
  id: '/changes',
  path: '/changes',
  getParentRoute: () => LangStudioEditorRoute,
} as any)
const LangStudioEditorRecipeOverviewRoute =
  LangStudioEditorRecipeOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => LangStudioEditorRecipeRoute,
  } as any)
const LangStudioEditorRecipeMainRoute =
  LangStudioEditorRecipeMainRouteImport.update({
    id: '/main',
    path: '/main',
    getParentRoute: () => LangStudioEditorRecipeRoute,
  } as any)
const LangStudioEditorLoot_tablePoolsRoute =
  LangStudioEditorLoot_tablePoolsRouteImport.update({
    id: '/pools',
    path: '/pools',
    getParentRoute: () => LangStudioEditorLoot_tableRoute,
  } as any)
const LangStudioEditorLoot_tableOverviewRoute =
  LangStudioEditorLoot_tableOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => LangStudioEditorLoot_tableRoute,
  } as any)
const LangStudioEditorLoot_tableMainRoute =
  LangStudioEditorLoot_tableMainRouteImport.update({
    id: '/main',
    path: '/main',
    getParentRoute: () => LangStudioEditorLoot_tableRoute,
  } as any)
const LangStudioEditorEnchantmentYggdrasilRoute =
  LangStudioEditorEnchantmentYggdrasilRouteImport.update({
    id: '/yggdrasil',
    path: '/yggdrasil',
    getParentRoute: () => LangStudioEditorEnchantmentRoute,
  } as any)
const LangStudioEditorEnchantmentTechnicalRoute =
  LangStudioEditorEnchantmentTechnicalRouteImport.update({
    id: '/technical',
    path: '/technical',
    getParentRoute: () => LangStudioEditorEnchantmentRoute,
  } as any)
const LangStudioEditorEnchantmentSlotsRoute =
  LangStudioEditorEnchantmentSlotsRouteImport.update({
    id: '/slots',
    path: '/slots',
    getParentRoute: () => LangStudioEditorEnchantmentRoute,
  } as any)
const LangStudioEditorEnchantmentSimulationRoute =
  LangStudioEditorEnchantmentSimulationRouteImport.update({
    id: '/simulation',
    path: '/simulation',
    getParentRoute: () => LangStudioEditorEnchantmentRoute,
  } as any)
const LangStudioEditorEnchantmentOverviewRoute =
  LangStudioEditorEnchantmentOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => LangStudioEditorEnchantmentRoute,
  } as any)
const LangStudioEditorEnchantmentMainRoute =
  LangStudioEditorEnchantmentMainRouteImport.update({
    id: '/main',
    path: '/main',
    getParentRoute: () => LangStudioEditorEnchantmentRoute,
  } as any)
const LangStudioEditorEnchantmentItemsRoute =
  LangStudioEditorEnchantmentItemsRouteImport.update({
    id: '/items',
    path: '/items',
    getParentRoute: () => LangStudioEditorEnchantmentRoute,
  } as any)
const LangStudioEditorEnchantmentFindRoute =
  LangStudioEditorEnchantmentFindRouteImport.update({
    id: '/find',
    path: '/find',
    getParentRoute: () => LangStudioEditorEnchantmentRoute,
  } as any)
const LangStudioEditorEnchantmentExclusiveRoute =
  LangStudioEditorEnchantmentExclusiveRouteImport.update({
    id: '/exclusive',
    path: '/exclusive',
    getParentRoute: () => LangStudioEditorEnchantmentRoute,
  } as any)
const LangStudioEditorEnchantmentDntRoute =
  LangStudioEditorEnchantmentDntRouteImport.update({
    id: '/dnt',
    path: '/dnt',
    getParentRoute: () => LangStudioEditorEnchantmentRoute,
  } as any)
const LangStudioEditorChangesVoxelRoute =
  LangStudioEditorChangesVoxelRouteImport.update({
    id: '/voxel',
    path: '/voxel',
    getParentRoute: () => LangStudioEditorChangesRoute,
  } as any)
const LangStudioEditorChangesPatchRoute =
  LangStudioEditorChangesPatchRouteImport.update({
    id: '/patch',
    path: '/patch',
    getParentRoute: () => LangStudioEditorChangesRoute,
  } as any)
const LangStudioEditorChangesMainRoute =
  LangStudioEditorChangesMainRouteImport.update({
    id: '/main',
    path: '/main',
    getParentRoute: () => LangStudioEditorChangesRoute,
  } as any)
const LangStudioEditorChangesEditRoute =
  LangStudioEditorChangesEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LangStudioEditorChangesRoute,
  } as any)
const LangStudioEditorChangesDiffRoute =
  LangStudioEditorChangesDiffRouteImport.update({
    id: '/diff',
    path: '/diff',
    getParentRoute: () => LangStudioEditorChangesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/auth': typeof AuthRoute
  '/$lang/world': typeof LangWorldRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/studio/editor': typeof LangStudioEditorRouteWithChildren
  '/$lang/studio/editor/changes': typeof LangStudioEditorChangesRouteWithChildren
  '/$lang/studio/editor/debug': typeof LangStudioEditorDebugRoute
  '/$lang/studio/editor/enchantment': typeof LangStudioEditorEnchantmentRouteWithChildren
  '/$lang/studio/editor/github': typeof LangStudioEditorGithubRoute
  '/$lang/studio/editor/loot_table': typeof LangStudioEditorLoot_tableRouteWithChildren
  '/$lang/studio/editor/recipe': typeof LangStudioEditorRecipeRouteWithChildren
  '/$lang/studio/editor/changes/diff': typeof LangStudioEditorChangesDiffRoute
  '/$lang/studio/editor/changes/edit': typeof LangStudioEditorChangesEditRoute
  '/$lang/studio/editor/changes/main': typeof LangStudioEditorChangesMainRoute
  '/$lang/studio/editor/changes/patch': typeof LangStudioEditorChangesPatchRoute
  '/$lang/studio/editor/changes/voxel': typeof LangStudioEditorChangesVoxelRoute
  '/$lang/studio/editor/enchantment/dnt': typeof LangStudioEditorEnchantmentDntRoute
  '/$lang/studio/editor/enchantment/exclusive': typeof LangStudioEditorEnchantmentExclusiveRoute
  '/$lang/studio/editor/enchantment/find': typeof LangStudioEditorEnchantmentFindRoute
  '/$lang/studio/editor/enchantment/items': typeof LangStudioEditorEnchantmentItemsRoute
  '/$lang/studio/editor/enchantment/main': typeof LangStudioEditorEnchantmentMainRoute
  '/$lang/studio/editor/enchantment/overview': typeof LangStudioEditorEnchantmentOverviewRoute
  '/$lang/studio/editor/enchantment/simulation': typeof LangStudioEditorEnchantmentSimulationRoute
  '/$lang/studio/editor/enchantment/slots': typeof LangStudioEditorEnchantmentSlotsRoute
  '/$lang/studio/editor/enchantment/technical': typeof LangStudioEditorEnchantmentTechnicalRoute
  '/$lang/studio/editor/enchantment/yggdrasil': typeof LangStudioEditorEnchantmentYggdrasilRoute
  '/$lang/studio/editor/loot_table/main': typeof LangStudioEditorLoot_tableMainRoute
  '/$lang/studio/editor/loot_table/overview': typeof LangStudioEditorLoot_tableOverviewRoute
  '/$lang/studio/editor/loot_table/pools': typeof LangStudioEditorLoot_tablePoolsRoute
  '/$lang/studio/editor/recipe/main': typeof LangStudioEditorRecipeMainRoute
  '/$lang/studio/editor/recipe/overview': typeof LangStudioEditorRecipeOverviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/$lang/world': typeof LangWorldRoute
  '/$lang': typeof LangIndexRoute
  '/$lang/studio/editor': typeof LangStudioEditorRouteWithChildren
  '/$lang/studio/editor/changes': typeof LangStudioEditorChangesRouteWithChildren
  '/$lang/studio/editor/debug': typeof LangStudioEditorDebugRoute
  '/$lang/studio/editor/enchantment': typeof LangStudioEditorEnchantmentRouteWithChildren
  '/$lang/studio/editor/github': typeof LangStudioEditorGithubRoute
  '/$lang/studio/editor/loot_table': typeof LangStudioEditorLoot_tableRouteWithChildren
  '/$lang/studio/editor/recipe': typeof LangStudioEditorRecipeRouteWithChildren
  '/$lang/studio/editor/changes/diff': typeof LangStudioEditorChangesDiffRoute
  '/$lang/studio/editor/changes/edit': typeof LangStudioEditorChangesEditRoute
  '/$lang/studio/editor/changes/main': typeof LangStudioEditorChangesMainRoute
  '/$lang/studio/editor/changes/patch': typeof LangStudioEditorChangesPatchRoute
  '/$lang/studio/editor/changes/voxel': typeof LangStudioEditorChangesVoxelRoute
  '/$lang/studio/editor/enchantment/dnt': typeof LangStudioEditorEnchantmentDntRoute
  '/$lang/studio/editor/enchantment/exclusive': typeof LangStudioEditorEnchantmentExclusiveRoute
  '/$lang/studio/editor/enchantment/find': typeof LangStudioEditorEnchantmentFindRoute
  '/$lang/studio/editor/enchantment/items': typeof LangStudioEditorEnchantmentItemsRoute
  '/$lang/studio/editor/enchantment/main': typeof LangStudioEditorEnchantmentMainRoute
  '/$lang/studio/editor/enchantment/overview': typeof LangStudioEditorEnchantmentOverviewRoute
  '/$lang/studio/editor/enchantment/simulation': typeof LangStudioEditorEnchantmentSimulationRoute
  '/$lang/studio/editor/enchantment/slots': typeof LangStudioEditorEnchantmentSlotsRoute
  '/$lang/studio/editor/enchantment/technical': typeof LangStudioEditorEnchantmentTechnicalRoute
  '/$lang/studio/editor/enchantment/yggdrasil': typeof LangStudioEditorEnchantmentYggdrasilRoute
  '/$lang/studio/editor/loot_table/main': typeof LangStudioEditorLoot_tableMainRoute
  '/$lang/studio/editor/loot_table/overview': typeof LangStudioEditorLoot_tableOverviewRoute
  '/$lang/studio/editor/loot_table/pools': typeof LangStudioEditorLoot_tablePoolsRoute
  '/$lang/studio/editor/recipe/main': typeof LangStudioEditorRecipeMainRoute
  '/$lang/studio/editor/recipe/overview': typeof LangStudioEditorRecipeOverviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$lang': typeof LangRouteWithChildren
  '/auth': typeof AuthRoute
  '/$lang/world': typeof LangWorldRoute
  '/$lang/': typeof LangIndexRoute
  '/$lang/studio/editor': typeof LangStudioEditorRouteWithChildren
  '/$lang/studio/editor/changes': typeof LangStudioEditorChangesRouteWithChildren
  '/$lang/studio/editor/debug': typeof LangStudioEditorDebugRoute
  '/$lang/studio/editor/enchantment': typeof LangStudioEditorEnchantmentRouteWithChildren
  '/$lang/studio/editor/github': typeof LangStudioEditorGithubRoute
  '/$lang/studio/editor/loot_table': typeof LangStudioEditorLoot_tableRouteWithChildren
  '/$lang/studio/editor/recipe': typeof LangStudioEditorRecipeRouteWithChildren
  '/$lang/studio/editor/changes/diff': typeof LangStudioEditorChangesDiffRoute
  '/$lang/studio/editor/changes/edit': typeof LangStudioEditorChangesEditRoute
  '/$lang/studio/editor/changes/main': typeof LangStudioEditorChangesMainRoute
  '/$lang/studio/editor/changes/patch': typeof LangStudioEditorChangesPatchRoute
  '/$lang/studio/editor/changes/voxel': typeof LangStudioEditorChangesVoxelRoute
  '/$lang/studio/editor/enchantment/dnt': typeof LangStudioEditorEnchantmentDntRoute
  '/$lang/studio/editor/enchantment/exclusive': typeof LangStudioEditorEnchantmentExclusiveRoute
  '/$lang/studio/editor/enchantment/find': typeof LangStudioEditorEnchantmentFindRoute
  '/$lang/studio/editor/enchantment/items': typeof LangStudioEditorEnchantmentItemsRoute
  '/$lang/studio/editor/enchantment/main': typeof LangStudioEditorEnchantmentMainRoute
  '/$lang/studio/editor/enchantment/overview': typeof LangStudioEditorEnchantmentOverviewRoute
  '/$lang/studio/editor/enchantment/simulation': typeof LangStudioEditorEnchantmentSimulationRoute
  '/$lang/studio/editor/enchantment/slots': typeof LangStudioEditorEnchantmentSlotsRoute
  '/$lang/studio/editor/enchantment/technical': typeof LangStudioEditorEnchantmentTechnicalRoute
  '/$lang/studio/editor/enchantment/yggdrasil': typeof LangStudioEditorEnchantmentYggdrasilRoute
  '/$lang/studio/editor/loot_table/main': typeof LangStudioEditorLoot_tableMainRoute
  '/$lang/studio/editor/loot_table/overview': typeof LangStudioEditorLoot_tableOverviewRoute
  '/$lang/studio/editor/loot_table/pools': typeof LangStudioEditorLoot_tablePoolsRoute
  '/$lang/studio/editor/recipe/main': typeof LangStudioEditorRecipeMainRoute
  '/$lang/studio/editor/recipe/overview': typeof LangStudioEditorRecipeOverviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$lang'
    | '/auth'
    | '/$lang/world'
    | '/$lang/'
    | '/$lang/studio/editor'
    | '/$lang/studio/editor/changes'
    | '/$lang/studio/editor/debug'
    | '/$lang/studio/editor/enchantment'
    | '/$lang/studio/editor/github'
    | '/$lang/studio/editor/loot_table'
    | '/$lang/studio/editor/recipe'
    | '/$lang/studio/editor/changes/diff'
    | '/$lang/studio/editor/changes/edit'
    | '/$lang/studio/editor/changes/main'
    | '/$lang/studio/editor/changes/patch'
    | '/$lang/studio/editor/changes/voxel'
    | '/$lang/studio/editor/enchantment/dnt'
    | '/$lang/studio/editor/enchantment/exclusive'
    | '/$lang/studio/editor/enchantment/find'
    | '/$lang/studio/editor/enchantment/items'
    | '/$lang/studio/editor/enchantment/main'
    | '/$lang/studio/editor/enchantment/overview'
    | '/$lang/studio/editor/enchantment/simulation'
    | '/$lang/studio/editor/enchantment/slots'
    | '/$lang/studio/editor/enchantment/technical'
    | '/$lang/studio/editor/enchantment/yggdrasil'
    | '/$lang/studio/editor/loot_table/main'
    | '/$lang/studio/editor/loot_table/overview'
    | '/$lang/studio/editor/loot_table/pools'
    | '/$lang/studio/editor/recipe/main'
    | '/$lang/studio/editor/recipe/overview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/$lang/world'
    | '/$lang'
    | '/$lang/studio/editor'
    | '/$lang/studio/editor/changes'
    | '/$lang/studio/editor/debug'
    | '/$lang/studio/editor/enchantment'
    | '/$lang/studio/editor/github'
    | '/$lang/studio/editor/loot_table'
    | '/$lang/studio/editor/recipe'
    | '/$lang/studio/editor/changes/diff'
    | '/$lang/studio/editor/changes/edit'
    | '/$lang/studio/editor/changes/main'
    | '/$lang/studio/editor/changes/patch'
    | '/$lang/studio/editor/changes/voxel'
    | '/$lang/studio/editor/enchantment/dnt'
    | '/$lang/studio/editor/enchantment/exclusive'
    | '/$lang/studio/editor/enchantment/find'
    | '/$lang/studio/editor/enchantment/items'
    | '/$lang/studio/editor/enchantment/main'
    | '/$lang/studio/editor/enchantment/overview'
    | '/$lang/studio/editor/enchantment/simulation'
    | '/$lang/studio/editor/enchantment/slots'
    | '/$lang/studio/editor/enchantment/technical'
    | '/$lang/studio/editor/enchantment/yggdrasil'
    | '/$lang/studio/editor/loot_table/main'
    | '/$lang/studio/editor/loot_table/overview'
    | '/$lang/studio/editor/loot_table/pools'
    | '/$lang/studio/editor/recipe/main'
    | '/$lang/studio/editor/recipe/overview'
  id:
    | '__root__'
    | '/'
    | '/$lang'
    | '/auth'
    | '/$lang/world'
    | '/$lang/'
    | '/$lang/studio/editor'
    | '/$lang/studio/editor/changes'
    | '/$lang/studio/editor/debug'
    | '/$lang/studio/editor/enchantment'
    | '/$lang/studio/editor/github'
    | '/$lang/studio/editor/loot_table'
    | '/$lang/studio/editor/recipe'
    | '/$lang/studio/editor/changes/diff'
    | '/$lang/studio/editor/changes/edit'
    | '/$lang/studio/editor/changes/main'
    | '/$lang/studio/editor/changes/patch'
    | '/$lang/studio/editor/changes/voxel'
    | '/$lang/studio/editor/enchantment/dnt'
    | '/$lang/studio/editor/enchantment/exclusive'
    | '/$lang/studio/editor/enchantment/find'
    | '/$lang/studio/editor/enchantment/items'
    | '/$lang/studio/editor/enchantment/main'
    | '/$lang/studio/editor/enchantment/overview'
    | '/$lang/studio/editor/enchantment/simulation'
    | '/$lang/studio/editor/enchantment/slots'
    | '/$lang/studio/editor/enchantment/technical'
    | '/$lang/studio/editor/enchantment/yggdrasil'
    | '/$lang/studio/editor/loot_table/main'
    | '/$lang/studio/editor/loot_table/overview'
    | '/$lang/studio/editor/loot_table/pools'
    | '/$lang/studio/editor/recipe/main'
    | '/$lang/studio/editor/recipe/overview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LangRoute: typeof LangRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang': {
      id: '/$lang'
      path: '/$lang'
      fullPath: '/$lang'
      preLoaderRoute: typeof LangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$lang/': {
      id: '/$lang/'
      path: '/'
      fullPath: '/$lang/'
      preLoaderRoute: typeof LangIndexRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/world': {
      id: '/$lang/world'
      path: '/world'
      fullPath: '/$lang/world'
      preLoaderRoute: typeof LangWorldRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/studio/editor': {
      id: '/$lang/studio/editor'
      path: '/studio/editor'
      fullPath: '/$lang/studio/editor'
      preLoaderRoute: typeof LangStudioEditorRouteImport
      parentRoute: typeof LangRoute
    }
    '/$lang/studio/editor/recipe': {
      id: '/$lang/studio/editor/recipe'
      path: '/recipe'
      fullPath: '/$lang/studio/editor/recipe'
      preLoaderRoute: typeof LangStudioEditorRecipeRouteImport
      parentRoute: typeof LangStudioEditorRoute
    }
    '/$lang/studio/editor/loot_table': {
      id: '/$lang/studio/editor/loot_table'
      path: '/loot_table'
      fullPath: '/$lang/studio/editor/loot_table'
      preLoaderRoute: typeof LangStudioEditorLoot_tableRouteImport
      parentRoute: typeof LangStudioEditorRoute
    }
    '/$lang/studio/editor/github': {
      id: '/$lang/studio/editor/github'
      path: '/github'
      fullPath: '/$lang/studio/editor/github'
      preLoaderRoute: typeof LangStudioEditorGithubRouteImport
      parentRoute: typeof LangStudioEditorRoute
    }
    '/$lang/studio/editor/enchantment': {
      id: '/$lang/studio/editor/enchantment'
      path: '/enchantment'
      fullPath: '/$lang/studio/editor/enchantment'
      preLoaderRoute: typeof LangStudioEditorEnchantmentRouteImport
      parentRoute: typeof LangStudioEditorRoute
    }
    '/$lang/studio/editor/debug': {
      id: '/$lang/studio/editor/debug'
      path: '/debug'
      fullPath: '/$lang/studio/editor/debug'
      preLoaderRoute: typeof LangStudioEditorDebugRouteImport
      parentRoute: typeof LangStudioEditorRoute
    }
    '/$lang/studio/editor/changes': {
      id: '/$lang/studio/editor/changes'
      path: '/changes'
      fullPath: '/$lang/studio/editor/changes'
      preLoaderRoute: typeof LangStudioEditorChangesRouteImport
      parentRoute: typeof LangStudioEditorRoute
    }
    '/$lang/studio/editor/recipe/overview': {
      id: '/$lang/studio/editor/recipe/overview'
      path: '/overview'
      fullPath: '/$lang/studio/editor/recipe/overview'
      preLoaderRoute: typeof LangStudioEditorRecipeOverviewRouteImport
      parentRoute: typeof LangStudioEditorRecipeRoute
    }
    '/$lang/studio/editor/recipe/main': {
      id: '/$lang/studio/editor/recipe/main'
      path: '/main'
      fullPath: '/$lang/studio/editor/recipe/main'
      preLoaderRoute: typeof LangStudioEditorRecipeMainRouteImport
      parentRoute: typeof LangStudioEditorRecipeRoute
    }
    '/$lang/studio/editor/loot_table/pools': {
      id: '/$lang/studio/editor/loot_table/pools'
      path: '/pools'
      fullPath: '/$lang/studio/editor/loot_table/pools'
      preLoaderRoute: typeof LangStudioEditorLoot_tablePoolsRouteImport
      parentRoute: typeof LangStudioEditorLoot_tableRoute
    }
    '/$lang/studio/editor/loot_table/overview': {
      id: '/$lang/studio/editor/loot_table/overview'
      path: '/overview'
      fullPath: '/$lang/studio/editor/loot_table/overview'
      preLoaderRoute: typeof LangStudioEditorLoot_tableOverviewRouteImport
      parentRoute: typeof LangStudioEditorLoot_tableRoute
    }
    '/$lang/studio/editor/loot_table/main': {
      id: '/$lang/studio/editor/loot_table/main'
      path: '/main'
      fullPath: '/$lang/studio/editor/loot_table/main'
      preLoaderRoute: typeof LangStudioEditorLoot_tableMainRouteImport
      parentRoute: typeof LangStudioEditorLoot_tableRoute
    }
    '/$lang/studio/editor/enchantment/yggdrasil': {
      id: '/$lang/studio/editor/enchantment/yggdrasil'
      path: '/yggdrasil'
      fullPath: '/$lang/studio/editor/enchantment/yggdrasil'
      preLoaderRoute: typeof LangStudioEditorEnchantmentYggdrasilRouteImport
      parentRoute: typeof LangStudioEditorEnchantmentRoute
    }
    '/$lang/studio/editor/enchantment/technical': {
      id: '/$lang/studio/editor/enchantment/technical'
      path: '/technical'
      fullPath: '/$lang/studio/editor/enchantment/technical'
      preLoaderRoute: typeof LangStudioEditorEnchantmentTechnicalRouteImport
      parentRoute: typeof LangStudioEditorEnchantmentRoute
    }
    '/$lang/studio/editor/enchantment/slots': {
      id: '/$lang/studio/editor/enchantment/slots'
      path: '/slots'
      fullPath: '/$lang/studio/editor/enchantment/slots'
      preLoaderRoute: typeof LangStudioEditorEnchantmentSlotsRouteImport
      parentRoute: typeof LangStudioEditorEnchantmentRoute
    }
    '/$lang/studio/editor/enchantment/simulation': {
      id: '/$lang/studio/editor/enchantment/simulation'
      path: '/simulation'
      fullPath: '/$lang/studio/editor/enchantment/simulation'
      preLoaderRoute: typeof LangStudioEditorEnchantmentSimulationRouteImport
      parentRoute: typeof LangStudioEditorEnchantmentRoute
    }
    '/$lang/studio/editor/enchantment/overview': {
      id: '/$lang/studio/editor/enchantment/overview'
      path: '/overview'
      fullPath: '/$lang/studio/editor/enchantment/overview'
      preLoaderRoute: typeof LangStudioEditorEnchantmentOverviewRouteImport
      parentRoute: typeof LangStudioEditorEnchantmentRoute
    }
    '/$lang/studio/editor/enchantment/main': {
      id: '/$lang/studio/editor/enchantment/main'
      path: '/main'
      fullPath: '/$lang/studio/editor/enchantment/main'
      preLoaderRoute: typeof LangStudioEditorEnchantmentMainRouteImport
      parentRoute: typeof LangStudioEditorEnchantmentRoute
    }
    '/$lang/studio/editor/enchantment/items': {
      id: '/$lang/studio/editor/enchantment/items'
      path: '/items'
      fullPath: '/$lang/studio/editor/enchantment/items'
      preLoaderRoute: typeof LangStudioEditorEnchantmentItemsRouteImport
      parentRoute: typeof LangStudioEditorEnchantmentRoute
    }
    '/$lang/studio/editor/enchantment/find': {
      id: '/$lang/studio/editor/enchantment/find'
      path: '/find'
      fullPath: '/$lang/studio/editor/enchantment/find'
      preLoaderRoute: typeof LangStudioEditorEnchantmentFindRouteImport
      parentRoute: typeof LangStudioEditorEnchantmentRoute
    }
    '/$lang/studio/editor/enchantment/exclusive': {
      id: '/$lang/studio/editor/enchantment/exclusive'
      path: '/exclusive'
      fullPath: '/$lang/studio/editor/enchantment/exclusive'
      preLoaderRoute: typeof LangStudioEditorEnchantmentExclusiveRouteImport
      parentRoute: typeof LangStudioEditorEnchantmentRoute
    }
    '/$lang/studio/editor/enchantment/dnt': {
      id: '/$lang/studio/editor/enchantment/dnt'
      path: '/dnt'
      fullPath: '/$lang/studio/editor/enchantment/dnt'
      preLoaderRoute: typeof LangStudioEditorEnchantmentDntRouteImport
      parentRoute: typeof LangStudioEditorEnchantmentRoute
    }
    '/$lang/studio/editor/changes/voxel': {
      id: '/$lang/studio/editor/changes/voxel'
      path: '/voxel'
      fullPath: '/$lang/studio/editor/changes/voxel'
      preLoaderRoute: typeof LangStudioEditorChangesVoxelRouteImport
      parentRoute: typeof LangStudioEditorChangesRoute
    }
    '/$lang/studio/editor/changes/patch': {
      id: '/$lang/studio/editor/changes/patch'
      path: '/patch'
      fullPath: '/$lang/studio/editor/changes/patch'
      preLoaderRoute: typeof LangStudioEditorChangesPatchRouteImport
      parentRoute: typeof LangStudioEditorChangesRoute
    }
    '/$lang/studio/editor/changes/main': {
      id: '/$lang/studio/editor/changes/main'
      path: '/main'
      fullPath: '/$lang/studio/editor/changes/main'
      preLoaderRoute: typeof LangStudioEditorChangesMainRouteImport
      parentRoute: typeof LangStudioEditorChangesRoute
    }
    '/$lang/studio/editor/changes/edit': {
      id: '/$lang/studio/editor/changes/edit'
      path: '/edit'
      fullPath: '/$lang/studio/editor/changes/edit'
      preLoaderRoute: typeof LangStudioEditorChangesEditRouteImport
      parentRoute: typeof LangStudioEditorChangesRoute
    }
    '/$lang/studio/editor/changes/diff': {
      id: '/$lang/studio/editor/changes/diff'
      path: '/diff'
      fullPath: '/$lang/studio/editor/changes/diff'
      preLoaderRoute: typeof LangStudioEditorChangesDiffRouteImport
      parentRoute: typeof LangStudioEditorChangesRoute
    }
  }
}

interface LangStudioEditorChangesRouteChildren {
  LangStudioEditorChangesDiffRoute: typeof LangStudioEditorChangesDiffRoute
  LangStudioEditorChangesEditRoute: typeof LangStudioEditorChangesEditRoute
  LangStudioEditorChangesMainRoute: typeof LangStudioEditorChangesMainRoute
  LangStudioEditorChangesPatchRoute: typeof LangStudioEditorChangesPatchRoute
  LangStudioEditorChangesVoxelRoute: typeof LangStudioEditorChangesVoxelRoute
}

const LangStudioEditorChangesRouteChildren: LangStudioEditorChangesRouteChildren =
  {
    LangStudioEditorChangesDiffRoute: LangStudioEditorChangesDiffRoute,
    LangStudioEditorChangesEditRoute: LangStudioEditorChangesEditRoute,
    LangStudioEditorChangesMainRoute: LangStudioEditorChangesMainRoute,
    LangStudioEditorChangesPatchRoute: LangStudioEditorChangesPatchRoute,
    LangStudioEditorChangesVoxelRoute: LangStudioEditorChangesVoxelRoute,
  }

const LangStudioEditorChangesRouteWithChildren =
  LangStudioEditorChangesRoute._addFileChildren(
    LangStudioEditorChangesRouteChildren,
  )

interface LangStudioEditorEnchantmentRouteChildren {
  LangStudioEditorEnchantmentDntRoute: typeof LangStudioEditorEnchantmentDntRoute
  LangStudioEditorEnchantmentExclusiveRoute: typeof LangStudioEditorEnchantmentExclusiveRoute
  LangStudioEditorEnchantmentFindRoute: typeof LangStudioEditorEnchantmentFindRoute
  LangStudioEditorEnchantmentItemsRoute: typeof LangStudioEditorEnchantmentItemsRoute
  LangStudioEditorEnchantmentMainRoute: typeof LangStudioEditorEnchantmentMainRoute
  LangStudioEditorEnchantmentOverviewRoute: typeof LangStudioEditorEnchantmentOverviewRoute
  LangStudioEditorEnchantmentSimulationRoute: typeof LangStudioEditorEnchantmentSimulationRoute
  LangStudioEditorEnchantmentSlotsRoute: typeof LangStudioEditorEnchantmentSlotsRoute
  LangStudioEditorEnchantmentTechnicalRoute: typeof LangStudioEditorEnchantmentTechnicalRoute
  LangStudioEditorEnchantmentYggdrasilRoute: typeof LangStudioEditorEnchantmentYggdrasilRoute
}

const LangStudioEditorEnchantmentRouteChildren: LangStudioEditorEnchantmentRouteChildren =
  {
    LangStudioEditorEnchantmentDntRoute: LangStudioEditorEnchantmentDntRoute,
    LangStudioEditorEnchantmentExclusiveRoute:
      LangStudioEditorEnchantmentExclusiveRoute,
    LangStudioEditorEnchantmentFindRoute: LangStudioEditorEnchantmentFindRoute,
    LangStudioEditorEnchantmentItemsRoute:
      LangStudioEditorEnchantmentItemsRoute,
    LangStudioEditorEnchantmentMainRoute: LangStudioEditorEnchantmentMainRoute,
    LangStudioEditorEnchantmentOverviewRoute:
      LangStudioEditorEnchantmentOverviewRoute,
    LangStudioEditorEnchantmentSimulationRoute:
      LangStudioEditorEnchantmentSimulationRoute,
    LangStudioEditorEnchantmentSlotsRoute:
      LangStudioEditorEnchantmentSlotsRoute,
    LangStudioEditorEnchantmentTechnicalRoute:
      LangStudioEditorEnchantmentTechnicalRoute,
    LangStudioEditorEnchantmentYggdrasilRoute:
      LangStudioEditorEnchantmentYggdrasilRoute,
  }

const LangStudioEditorEnchantmentRouteWithChildren =
  LangStudioEditorEnchantmentRoute._addFileChildren(
    LangStudioEditorEnchantmentRouteChildren,
  )

interface LangStudioEditorLoot_tableRouteChildren {
  LangStudioEditorLoot_tableMainRoute: typeof LangStudioEditorLoot_tableMainRoute
  LangStudioEditorLoot_tableOverviewRoute: typeof LangStudioEditorLoot_tableOverviewRoute
  LangStudioEditorLoot_tablePoolsRoute: typeof LangStudioEditorLoot_tablePoolsRoute
}

const LangStudioEditorLoot_tableRouteChildren: LangStudioEditorLoot_tableRouteChildren =
  {
    LangStudioEditorLoot_tableMainRoute: LangStudioEditorLoot_tableMainRoute,
    LangStudioEditorLoot_tableOverviewRoute:
      LangStudioEditorLoot_tableOverviewRoute,
    LangStudioEditorLoot_tablePoolsRoute: LangStudioEditorLoot_tablePoolsRoute,
  }

const LangStudioEditorLoot_tableRouteWithChildren =
  LangStudioEditorLoot_tableRoute._addFileChildren(
    LangStudioEditorLoot_tableRouteChildren,
  )

interface LangStudioEditorRecipeRouteChildren {
  LangStudioEditorRecipeMainRoute: typeof LangStudioEditorRecipeMainRoute
  LangStudioEditorRecipeOverviewRoute: typeof LangStudioEditorRecipeOverviewRoute
}

const LangStudioEditorRecipeRouteChildren: LangStudioEditorRecipeRouteChildren =
  {
    LangStudioEditorRecipeMainRoute: LangStudioEditorRecipeMainRoute,
    LangStudioEditorRecipeOverviewRoute: LangStudioEditorRecipeOverviewRoute,
  }

const LangStudioEditorRecipeRouteWithChildren =
  LangStudioEditorRecipeRoute._addFileChildren(
    LangStudioEditorRecipeRouteChildren,
  )

interface LangStudioEditorRouteChildren {
  LangStudioEditorChangesRoute: typeof LangStudioEditorChangesRouteWithChildren
  LangStudioEditorDebugRoute: typeof LangStudioEditorDebugRoute
  LangStudioEditorEnchantmentRoute: typeof LangStudioEditorEnchantmentRouteWithChildren
  LangStudioEditorGithubRoute: typeof LangStudioEditorGithubRoute
  LangStudioEditorLoot_tableRoute: typeof LangStudioEditorLoot_tableRouteWithChildren
  LangStudioEditorRecipeRoute: typeof LangStudioEditorRecipeRouteWithChildren
}

const LangStudioEditorRouteChildren: LangStudioEditorRouteChildren = {
  LangStudioEditorChangesRoute: LangStudioEditorChangesRouteWithChildren,
  LangStudioEditorDebugRoute: LangStudioEditorDebugRoute,
  LangStudioEditorEnchantmentRoute:
    LangStudioEditorEnchantmentRouteWithChildren,
  LangStudioEditorGithubRoute: LangStudioEditorGithubRoute,
  LangStudioEditorLoot_tableRoute: LangStudioEditorLoot_tableRouteWithChildren,
  LangStudioEditorRecipeRoute: LangStudioEditorRecipeRouteWithChildren,
}

const LangStudioEditorRouteWithChildren =
  LangStudioEditorRoute._addFileChildren(LangStudioEditorRouteChildren)

interface LangRouteChildren {
  LangWorldRoute: typeof LangWorldRoute
  LangIndexRoute: typeof LangIndexRoute
  LangStudioEditorRoute: typeof LangStudioEditorRouteWithChildren
}

const LangRouteChildren: LangRouteChildren = {
  LangWorldRoute: LangWorldRoute,
  LangIndexRoute: LangIndexRoute,
  LangStudioEditorRoute: LangStudioEditorRouteWithChildren,
}

const LangRouteWithChildren = LangRoute._addFileChildren(LangRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LangRoute: LangRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
